#!/bin/sh 
# wrapper that executes the TCL-TK frontend to the (IN)UTILE program
#				Stefan Schippers


# removing existing TK_LIBRARY variable avoids some clobbering 
# with existing old libraries seen on Solaris systems
unset TK_LIBRARY
TCL_LIBRARY=/home/schippes/lib_solaris/tcl8.3
export TCL_LIBRARY
MY_PREFIX=/home/schippes
PATH=${MY_PREFIX}/bin_solaris:${MY_PREFIX}/utile3:/bin:/usr/bin:$PATH
LD_LIBRARY_PATH=${MY_PREFIX}/lib_solaris:$LD_LIBRARY_PATH
export MY_PREFIX
export PATH
export LD_LIBRARY_PATH
utile.tcl $@
