/*************************************************************/
/* Generated by scconfig - DO NOT EDIT - will be overwritten */
/* Source: config.h.in; to regenerate run ./configure        */
/*************************************************************/

/* Define to 1 if cairo is available and is to be used */
/* #define HAS_CAIRO 1*/

/* Define to 1 if Xlib's xcb is available */
/* #define HAS_XCB 1 */

/* Define to 1 if Xlib's xrender is available */
#define HAS_XRENDER 1

/* Define to 1 if popen(3) is available */
#define HAS_POPEN 0
#define PREFIX               "C:/.xschem/tmp"
#define USER_CONF_DIR        "userConf"

/* Extra includes required by the detected libs (may be empty): */

#define _XOPEN_SOURCE


